#!/usr/bin/env node
// Download the woff2 files Daylight uses and write a local @font-face sheet, so
// the game keeps its typeface on a plane and never phones Google on open.
// Latin + latin-ext only: latin-ext carries the pinyin tone marks the Mandarin
// set needs. CJK is deliberately not bundled — hanzi render from the system stack.

import { mkdir, writeFile } from "node:fs/promises";

const OUT_DIR = "/home/user/stu-bot/app/fonts";
const CSS_OUT = "/home/user/stu-bot/app/fonts.css";

const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/120.0 Safari/537.36";

const FAMILIES = [
  { slug: "bricolage", req: "Bricolage+Grotesque:opsz,wght@12..96,200..800" },
  { slug: "instrument", req: "Instrument+Sans:wght@400..700" },
  { slug: "jbmono", req: "JetBrains+Mono:wght@400..800" },
];

const KEEP = new Set(["latin", "latin-ext"]);

async function css(req) {
  const r = await fetch(
    `https://fonts.googleapis.com/css2?family=${req}&display=swap`,
    { headers: { "User-Agent": UA } }
  );
  if (!r.ok) throw new Error(`css ${r.status} ${req}`);
  return r.text();
}

function blocks(text) {
  const out = [];
  const re = /\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g;
  let m;
  while ((m = re.exec(text))) out.push({ subset: m[1], block: m[2] });
  return out;
}

await mkdir(OUT_DIR, { recursive: true });
let sheet =
  "/* Self-hosted so the game keeps its typeface offline and never calls Google.\n" +
  "   Generated by scripts/fetch-fonts.mjs — do not hand-edit. */\n";

for (const f of FAMILIES) {
  const text = await css(f.req);
  const wanted = blocks(text).filter((b) => KEEP.has(b.subset));
  if (!wanted.length) throw new Error(`no kept subsets for ${f.slug}`);
  for (const { subset, block } of wanted) {
    const url = /src:\s*url\((https:\/\/[^)]+)\)/.exec(block);
    if (!url) throw new Error(`no url in ${f.slug}/${subset}`);
    const bin = await fetch(url[1], { headers: { "User-Agent": UA } });
    if (!bin.ok) throw new Error(`font ${bin.status} ${f.slug}/${subset}`);
    const name = `${f.slug}-${subset}.woff2`;
    await writeFile(`${OUT_DIR}/${name}`, Buffer.from(await bin.arrayBuffer()));
    sheet +=
      "\n" +
      block.replace(/src:\s*url\(https:\/\/[^)]+\)/, `src: url(fonts/${name})`) +
      "\n";
    console.log("ok", name);
  }
}

await writeFile(CSS_OUT, sheet);
console.log("wrote", CSS_OUT, sheet.length, "bytes");
